version: "3.9"

services:
  nexus:
    container_name: "nexus-composed"
    image: sonatype/nexus3
    volumes:
      - nexus-data:/nexus-data
    restart: unless-stopped
  nginx:
    container_name: "nginx-nexus-composed"
    image: library/nginx
    ports:
      - "9000:80"
      - "9001:443"
      - "9005:444"
    volumes:
      - ./localhost.crt:/etc/ssl/certs/localhost.crt
      - ./localhost.key:/etc/ssl/private/localhost.key
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
volumes:
  nexus-data: