name: webui-ollama

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - ./open-webui-data:/app/backend/data
    ports:
      - 3000:8080
    environment:
      - "OLLAMA_BASE_URL=http://host.docker.internal:11434"
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
