version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.11.7-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq-data:/var/lib/rabbitmq/
        - rabbitmq-log:/var/log/rabbitmq
    networks:
        - rabbitmq_net

volumes:
  rabbitmq-data:
    driver: local
  rabbitmq-log:
    driver: local

networks:
  rabbitmq_net:
    driver: bridge      