groups: 

- name: test
  rules:
  - alert: Instance Down
    expr: up == 0
    for: 0m
    labels:
      severity: critical
      context: app-state
    annotations:
      summary: "Prometheus target missing (instance {{ $labels.instance }})"
      description: "A Prometheus target has disappeared. An exporter might be crashed. VALUE = {{ $value }}  LABELS: {{ $labels }}"