version: "3.9"

services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    hostname: zookeeper
    restart: unless-stopped
    ports:
      - 2181:2181
    volumes:
      - zookeeper_data:/bitnami
    environment:
      TZ: Europe/Moscow
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    image: bitnami/kafka:3.2
    container_name: kafka
    hostname: kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    volumes:
      - kafka_data:/bitnami
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      TZ: Europe/Moscow
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://host.docker.internal:9092"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    
  #kafka-connect:
  #  image: bitnami/kafka:3.2
  #  container_name: kafka_connect
  #  hostname: kafka-connect
  #  restart: unless-stopped
  #  ports:
  #    - '8083:8083'
  #  volumes:
  #    - kafka_connect_data:/bitnami
  #  depends_on:
  #    - zookeeper
  #    - kafka
  #  command: /opt/bitnami/kafka/bin/connect-distributed.sh /opt/bitnami/kafka/config/connect-distributed.properties
    
  kowl:
    image: pmatrosov/kowl:latest
    container_name: kowl
    hostname: kowl
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - 8080:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: /bin/sh
    command: -c "echo \"$$KOWL_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      TZ: Europe/Moscow
      CONFIG_FILEPATH: /tmp/config.yml
      KOWL_CONFIG_FILE: |
        kafka:
          brokers: ["host.docker.internal:9092"]
          messagePack:
            enabled: true
        connect:
          enabled: true
          clusters:
            name: debezium
            url: http://debezium:8083

  debezium:
    image: debezium/connect:1.9
    container_name: debezium
    hostname: debezium
    depends_on:
      - kafka
    profiles:
      - debezium
    ports:
      - 8083:8083
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      TZ: Europe/Moscow
      BOOTSTRAP_SERVERS: 'kafka:9092'
      GROUP_ID: dbz-connect-group
      REST_ADVERTISED_HOST_NAME: debezium
      CONFIG_STORAGE_TOPIC: dbz-connect-configs
      OFFSET_STORAGE_TOPIC: dbz-connect-offsets
      STATUS_STORAGE_TOPIC: dbz-connect-status       

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local  
  #kafka_connect_data:
  #  driver: local  