version: "3.9"
services:
  node1:
    image: mongo:latest
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    networks:
      cluster:
        aliases:
          - node1.couchdb.local
    volumes:
      - ./data1:/data/db

networks:
  cluster: